root = "."
tmp_dir = "tmp/air"

[build]
cmd = "templ generate -v -log-level -path ./src/template && go build -o ./tmp/air/main ./cmd/main.go"
bin = "tmp/air/main"
include_ext = ["go", "html", "js", "ts", "css", "templ"]
exclude_dir = ["tmp", "doc"]
exclude_regex = ["\\_templ\\.go$"]
watch_dir = "."

[log]
log = "build.log"
time = true
