services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: heracles
    ports:
      - "4200:4200"  # Angular
      - "9876:9876"  # Karma
      - "9222:9222"  # Remote Debugging de Chrome
    volumes:
      - .:/app
