services:
  heracles-front:
    build:
      target: development  # On utilise la phase dev du Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-nseven"
      - "traefik.http.routers.heracles-front.rule=Host(`heracles.dev`)"
      - "traefik.http.routers.heracles-front.entrypoints=websecure"
      - "traefik.http.routers.heracles-front.tls=true"
      - "traefik.http.routers.heracles-front.tls.certresolver=default"
      - "traefik.http.services.heracles-front.loadbalancer.server.port=4200"
    environment:
      - NODE_ENV=development
