services:
  app:
    container_name: heracles
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app:delegated
    networks:
      - traefik-nseven

networks:
  traefik-nseven:
    external: true
