services:
  heracles-front:
    container_name: heracles-front
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app:delegated
    networks:
      - traefik-nseven

networks:
  traefik-nseven:
    external: true
