services:
  heracles-go:
    build:
      target: dev
      context: ..
      dockerfile: docker/Dockerfile
    container_name: heracles-go
    image: heracles:dev
    volumes:
      - ../:/app
    env_file:
      - ../.env
    networks:
      - traefik-nseven
      - heracles

networks:
  heracles:
    driver: bridge
  traefik-nseven:
    external: true